package maths2;
//@author ChibuezePaul

import java.text.SimpleDateFormat;
import java.util.*;
import javax.swing.*;
import static javax.swing.JOptionPane.*;

public class BasicCalculator extends javax.swing.JFrame {

    /**
     * Creates new form MyFrame
     */
    public BasicCalculator() {
        initComponents();
        setLocationRelativeTo(JOptionPane.getRootFrame());
        setTitle("ISoft Basic Calculator");
        setIconImage(new ImageIcon(getClass().getResource("icons8_Student_Center_20px_4.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panCalc = new javax.swing.JPanel();
        txtNum1 = new javax.swing.JTextField();
        txtNum2 = new javax.swing.JTextField();
        btnOk = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rbtnSub = new javax.swing.JRadioButton();
        rbtnMult = new javax.swing.JRadioButton();
        rbtnDiv = new javax.swing.JRadioButton();
        rbtnMod = new javax.swing.JRadioButton();
        rbtnAdd = new javax.swing.JRadioButton();
        btnClr = new javax.swing.JButton();
        lbDate = new javax.swing.JLabel();
        lbTime = new javax.swing.JLabel();
        lbCdate = new javax.swing.JLabel();
        lbCtime = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtResult0 = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setResizable(false);
        setSize(new java.awt.Dimension(720, 610));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        panCalc.setAlignmentX(100.0F);
        panCalc.setAlignmentY(100.0F);
        panCalc.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panCalc.setMaximumSize(new java.awt.Dimension(0, 0));
        panCalc.setMinimumSize(new java.awt.Dimension(481, 223));

        txtNum1.setName(""); // NOI18N
        txtNum1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNum1KeyTyped(evt);
            }
        });

        txtNum2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNum2KeyTyped(evt);
            }
        });

        btnOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maths2/icons8_Reply_All_Arrow_25px.png"))); // NOI18N
        btnOk.setBorder(null);
        btnOk.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnOk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnOkMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        jLabel1.setText("Enter first number");
        jLabel1.setFocusTraversalPolicyProvider(true);
        jLabel1.setName("lab1"); // NOI18N

        jLabel2.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        jLabel2.setText("Enter second number");
        jLabel2.setName("lab2"); // NOI18N

        jLabel3.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        jLabel3.setText("Result");
        jLabel3.setName("lab2"); // NOI18N

        buttonGroup1.add(rbtnSub);
        rbtnSub.setFont(new java.awt.Font("FormalScrp421 BT", 1, 12)); // NOI18N
        rbtnSub.setText("Subtraction");

        buttonGroup1.add(rbtnMult);
        rbtnMult.setFont(new java.awt.Font("FormalScrp421 BT", 1, 12)); // NOI18N
        rbtnMult.setText("Multiplication");

        buttonGroup1.add(rbtnDiv);
        rbtnDiv.setFont(new java.awt.Font("FormalScrp421 BT", 1, 12)); // NOI18N
        rbtnDiv.setText("Division");

        buttonGroup1.add(rbtnMod);
        rbtnMod.setFont(new java.awt.Font("FormalScrp421 BT", 1, 12)); // NOI18N
        rbtnMod.setText("Modulus");

        buttonGroup1.add(rbtnAdd);
        rbtnAdd.setFont(new java.awt.Font("FormalScrp421 BT", 1, 12)); // NOI18N
        rbtnAdd.setText("Addition");

        btnClr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maths2/icons8_Refresh_25px.png"))); // NOI18N
        btnClr.setBorder(null);
        btnClr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnClrMousePressed(evt);
            }
        });

        lbDate.setFont(new java.awt.Font("Exotc350 Bd BT", 0, 12)); // NOI18N

        lbTime.setFont(new java.awt.Font("Exotc350 Bd BT", 0, 12)); // NOI18N

        lbCdate.setFont(new java.awt.Font("Exotc350 Bd BT", 0, 15)); // NOI18N
        lbCdate.setText("Current Date:");

        lbCtime.setFont(new java.awt.Font("Exotc350 Bd BT", 0, 15)); // NOI18N
        lbCtime.setText("Current Time:");

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));

        jLabel4.setFont(new java.awt.Font("Gabriola", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Student's Basic Calculator");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(204, 0, 0));

        jLabel5.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maths/icons8_Info_20px_1.png"))); // NOI18N
        jLabel5.setText("ISoft");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, Short.MAX_VALUE)
        );

        txtResult0.setEditable(false);
        txtResult0.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));
        txtResult0.setFocusable(false);

        javax.swing.GroupLayout panCalcLayout = new javax.swing.GroupLayout(panCalc);
        panCalc.setLayout(panCalcLayout);
        panCalcLayout.setHorizontalGroup(
            panCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCalcLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panCalcLayout.createSequentialGroup()
                        .addComponent(lbCdate)
                        .addGap(12, 12, 12)
                        .addComponent(lbDate, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110)
                        .addComponent(lbCtime)
                        .addGap(10, 10, 10)
                        .addComponent(lbTime, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panCalcLayout.createSequentialGroup()
                        .addGroup(panCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panCalcLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnClr, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panCalcLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(panCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGroup(panCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panCalcLayout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addGroup(panCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(panCalcLayout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(txtResult0, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                                .addGroup(panCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtnMod, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rbtnSub)
                                    .addComponent(rbtnDiv)
                                    .addComponent(rbtnAdd)
                                    .addComponent(rbtnMult))))
                        .addGap(31, 31, 31))))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panCalcLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnClr, btnOk});

        panCalcLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtNum1, txtNum2});

        panCalcLayout.setVerticalGroup(
            panCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCalcLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(panCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbCdate)
                    .addComponent(lbDate, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCtime)
                    .addComponent(lbTime, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panCalcLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(panCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panCalcLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(70, 70, 70)
                                .addGroup(panCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtResult0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panCalcLayout.createSequentialGroup()
                                .addComponent(txtNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addGroup(panCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)))))
                    .addGroup(panCalcLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtnSub)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtnMult)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtnDiv)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtnMod)))
                .addGap(18, 18, 18)
                .addGroup(panCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClr, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panCalcLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {rbtnAdd, rbtnDiv, rbtnMod, rbtnMult, rbtnSub});

        panCalcLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnClr, btnOk});

        panCalcLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtNum1, txtNum2, txtResult0});

        txtNum1.getAccessibleContext().setAccessibleName("txt1");
        txtNum2.getAccessibleContext().setAccessibleName("txt2");
        btnOk.getAccessibleContext().setAccessibleName("btn1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panCalc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panCalc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    double result;

    private void btnOkMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOkMousePressed
        try {
            Double num3 = Double.parseDouble(txtNum1.getText());
            Double num4 = Double.parseDouble(txtNum2.getText());

            if (rbtnAdd.isSelected()) {
                result = num3 + num4;
                txtResult0.setValue((result));
            }
            if (rbtnSub.isSelected()) {
                result = num3 - num4;
                txtResult0.setValue((result));
            }
            if (rbtnMult.isSelected()) {
                result = num3 * num4;
                txtResult0.setValue((result));
            }
            if (rbtnDiv.isSelected()) {
                result = num3 / num4;
                txtResult0.setValue((result));
            }
            if (rbtnMod.isSelected()) {
                result = num3 % num4;
                txtResult0.setValue((result));
            }
            if (rbtnDiv.isSelected() && num4 == 0) {
                JOptionPane.showMessageDialog(null, "Cannot divide by Zero", "Math Error", ERROR_MESSAGE);
            }
            if (num3.isNaN() && num4.isNaN() && btnOk.isSelected()) {
                JOptionPane.showMessageDialog(null, "Input a numeric value", "InputError", 3);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "InputError", 2);
        }
    }//GEN-LAST:event_btnOkMousePressed

    private void btnClrMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClrMousePressed
        txtNum1.setText(null);
        txtNum2.setText(null);
        txtResult0.setText(null);
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_btnClrMousePressed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (JOptionPane.showConfirmDialog(null, "Exit Basic Calculator", "Student Companion",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            this.dispose();
            CompanionApp.main(null);
        }
    }//GEN-LAST:event_formWindowClosing

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Calendar timer = Calendar.getInstance();

        SimpleDateFormat myTimeFormat = new SimpleDateFormat("hh:mm");
        String myTime = (myTimeFormat.format(timer.getTime()));

        SimpleDateFormat myDateFormat = new SimpleDateFormat("dd MMMMMMMMM '\"'yy");
        String myDate = (myDateFormat.format(timer.getTime()));

        lbTime.setText(myTime);
        lbDate.setText(myDate);
    }//GEN-LAST:event_formWindowActivated

    private void txtNum1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNum1KeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNum1KeyTyped

    private void txtNum2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNum2KeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNum2KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BasicCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BasicCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BasicCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BasicCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new BasicCalculator().setVisible(true);
            new BasicCalculator().setResizable(false);

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClr;
    private javax.swing.JButton btnOk;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbCdate;
    private javax.swing.JLabel lbCtime;
    private javax.swing.JLabel lbDate;
    private javax.swing.JLabel lbTime;
    private javax.swing.JPanel panCalc;
    private javax.swing.JRadioButton rbtnAdd;
    private javax.swing.JRadioButton rbtnDiv;
    private javax.swing.JRadioButton rbtnMod;
    private javax.swing.JRadioButton rbtnMult;
    private javax.swing.JRadioButton rbtnSub;
    private javax.swing.JTextField txtNum1;
    private javax.swing.JTextField txtNum2;
    private javax.swing.JFormattedTextField txtResult0;
    // End of variables declaration//GEN-END:variables
}
